version: "3.8"

services:
  db:
    image: postgres:15
    container_name: poc-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: claimdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: poc-app
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  postgres_data:

